version: '3.8'

services:
  powiadomienia-admin:
    build: .
    container_name: powiadomienia-admin-bot
    restart: always
    ports:
      - "8086:8080"
    env_file:
      - .env
    environment:
      - TZ=Europe/Warsaw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
